LOOKUP_REQ = '1'
LOOKUP_REP = '2'
JOIN_REQ   = '3'
JOIN_REP   = '4'
LEAVE      = '5'
DISCOVER   = '6'
STOP       = '7'
MOV_DATA_REQ  = '8'
MOV_DATA_REP  = '9'
ACEPT_PRED = '10'
ACEPT_SUC  = '11'
GET_NODES  = '12'
CHECK_REQ  = '13'
CHECK_REP  = '14' 
SET_LEADER = '15'
REP_DATA_REQ = '16'
REP_DATA_REP = '17'
SET_DATA_REQ = '18'
SET_DATA_REP = '19'
SET_REP_DATA_REQ = '20'
GET_DATA_REQ  = '21'
GET_DATA_REP  = '22'
SET_NODES = '23'
CHECK_SUC ='24' 
CHECK_SUC_RESP = '25'
DEL_REP_DATA = '26'

#Creates and Updates
ADD_MEMBER_GROUP = '28'
ADD_MEMBER_GROUP_REP = '29'
CREATE_PROFILE = '30'
REP_PROFILE = '31'
CREATE_GROUP = '32'
REP_GROUP = '33'
CREATE_EVENT = '34'
REP_EVENT = '35'
UPDATE_MEETING = '36'
REP_UPDATE_MEETING = "37"
UPDATE_GROUP = '38'
REP_UPDATE_GROUP = '39'
UPDATE_HIERARCHY_LEVEL = '40'
REP_UPDATE_HIERARCHY_LEVEL = '41'
CREATE_GROUP_MEETING = '42'
REP_CREATE_GROUP_MEETING = '43'
CREATE_MEETING = '44'
REP_CREATE_MEETING = '45'
UPDATE_EVENT = '46'
REP_UPDATE_EVENT = '47'


#delete
DELETE_MEETING = '48'
DELETE_MEETING_REP = '49'
DELETE_MEMBER_GROUP = '50'
DELETE_MEMBER_GROUP_REP = '51'
DELETE_EVENT = '52'
DELETE_EVENT_REP = '53'
DELETE_NOTIFICATION = '54'
DELETE_NOTIFICATION_REP = '55'
DELETE_USER = '56'
DELETE_USER_REP = '57'
DELETE_GROUP = '58'
DELETE_GROUP_REP = '59'


#Queries
GET_PROFILE = '60'
GET_PROFILE_RESP = '61'
GET_NOTIFICATIONS = '62'
GET_NOTIF_RESP = '63'
GET_EVENTS = '64'
GET_EVENTS_RESP = '65'
GET_MEETING = '66'
GET_MEETING_RESP = '67'
GET_MEETINGS = '68'
GET_MEETINGS_RESP = '69'
GET_HIERARCHY_LEVEL = '70' 
GET_HIERARCHY_LEVEL_RESP = '71'
GET_GROUPS = '72'
GET_GROUPS_RESP = '73'
GET_GROUP = '74'
GET_GROUP_RESP = '75'
GET_EVENT = '76'
GET_EVENT_RESP = '77'
GET_GROUP_TYPE = '78'
GET_GROUP_TYPE_RESP = '79'
GET_USERS_IN_GROUP = '80'
GET_USERS_IN_GROUP_REP = '81'
GET_EVENTS_IN_GROUP = '82'
GET_EVENTS_IN_GROUP_REP = '83'
GET_INVITED_GROUPS = '84'
GET_INVITED_GROUPS_REP = '85'

MCAST_GRP = "224.0.0.1"
MCAST_PORT = 10003
NODE_TIMEOUT = 10

# Host y puertos
HOST = "0.0.0.0"
CLIENT_PORT = 65434  # Para la comunicación con clientes
SERVER_PORT = 65433  # Para la comunicación entre gestores
FILES_PORT = 65432
CHECK_PORT = 65431
HEARD_PORT = 65430