version: "3.8"

services:
  router:
    build:
      context: .
      dockerfile: docker/router.Dockerfile
    container_name: router
    cap_add:
      - NET_ADMIN
    networks:
      clients:
        ipv4_address: 10.0.20.254
      servers:
        ipv4_address: 10.0.21.254
    command: ["sleep", "infinity"] # Mantener el contenedor en ejecución

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    cap_add:
      - NET_ADMIN
    ports:
      - 3000:3000
      - 8080:8080
      - 8000:8000
    networks:
      - clients
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: ["sh", "-c", "./frontend.sh && npm run dev"]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    cap_add:
      - NET_ADMIN
    networks:
      - servers
    volumes:
      - ./backend:/app
    working_dir: /app
    command: ["sh", "-c", "./backend.sh && uvicorn app.main:app --host 0.0.0.0 --port 8000"]

networks:
  clients:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.20.0/24

  servers:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.21.0/24